packages:
  - .

allowBuilds:
  "@google/genai": true
  "@sentry/cli": true
  canvas: true
  esbuild: true
  protobufjs: false
  sharp: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - canvas

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver

storeDir: .pnpm-store/v11
