import { beforeEach, describe, expect, it, vi } from "vitest";
import type { InterviewQuestionPool } from "@/lib/db/schema";
import type { InterviewProfile } from "@/features/interviews/interview-profile";

const expireStalePendingPools = vi.fn();
const listReadyPoolsByFingerprint = vi.fn();
const listUserPoolIdsAmong = vi.fn();
const claimPendingPool = vi.fn();

vi.mock("@/features/interviews/server/interview-pool.repository", () => ({
  expireStalePendingPools: () => expireStalePendingPools(),
  listReadyPoolsByFingerprint: (fingerprint: string) =>
    listReadyPoolsByFingerprint(fingerprint),
  listUserPoolIdsAmong: (input: unknown) => listUserPoolIdsAmong(input),
  claimPendingPool: (input: unknown) => claimPendingPool(input),
}));

const { resolveInterviewPool } = await import(
  "@/features/interviews/server/interview-pool-cache.service"
);

const profile: InterviewProfile = {
  roleFamily: "frontend-engineering",
  seniorityBand: "senior",
  coreSkills: ["css", "react", "typescript"],
  secondarySkills: [],
  responsibilities: [],
  targetRequirements: [],
  topics: [],
};

function pool(overrides: Partial<InterviewQuestionPool> = {}) {
  return {
    id: "pool-1",
    fingerprint: "fp-1",
    status: "READY",
    poolVersion: 1,
    roleFamily: "frontend-engineering",
    seniorityBand: "senior",
    ...overrides,
  } as InterviewQuestionPool;
}

beforeEach(() => {
  vi.clearAllMocks();
  expireStalePendingPools.mockResolvedValue(undefined);
  listUserPoolIdsAmong.mockResolvedValue(new Set<string>());
});

describe("resolveInterviewPool", () => {
  it("always expires stale pending pools before deciding", async () => {
    listReadyPoolsByFingerprint.mockResolvedValue([]);
    claimPendingPool.mockResolvedValue({ claimed: true, pool: pool() });

    await resolveInterviewPool({ userId: "u1", fingerprint: "fp-1", profile });

    expect(expireStalePendingPools).toHaveBeenCalledTimes(1);
  });

  it("reuses an unused ready pool without touching the generator (cache hit)", async () => {
    listReadyPoolsByFingerprint.mockResolvedValue([
      pool({ id: "p1", poolVersion: 1 }),
      pool({ id: "p2", poolVersion: 2 }),
    ]);

    const result = await resolveInterviewPool({
      userId: "u1",
      fingerprint: "fp-1",
      profile,
    });

    expect(result).toEqual({
      status: "reuse",
      pool: pool({ id: "p1", poolVersion: 1 }),
      recycled: false,
    });
    expect(claimPendingPool).not.toHaveBeenCalled();
  });

  it("shares a pool generated by another user (cross-user reuse)", async () => {
    listReadyPoolsByFingerprint.mockResolvedValue([
      pool({ id: "from-user-a", poolVersion: 1 }),
    ]);
    listUserPoolIdsAmong.mockResolvedValue(new Set<string>());

    const result = await resolveInterviewPool({
      userId: "user-b",
      fingerprint: "fp-1",
      profile,
    });

    expect(result.status).toBe("reuse");
    expect(claimPendingPool).not.toHaveBeenCalled();
  });

  it("picks the lowest unused version when some are already used", async () => {
    listReadyPoolsByFingerprint.mockResolvedValue([
      pool({ id: "p1", poolVersion: 1 }),
      pool({ id: "p2", poolVersion: 2 }),
      pool({ id: "p3", poolVersion: 3 }),
    ]);
    listUserPoolIdsAmong.mockResolvedValue(new Set(["p1"]));

    const result = await resolveInterviewPool({
      userId: "u1",
      fingerprint: "fp-1",
      profile,
    });

    expect(result).toMatchObject({ status: "reuse", recycled: false });
    if (result.status === "reuse") {
      expect(result.pool.id).toBe("p2");
    }
  });

  it("claims a generation slot on a cache miss", async () => {
    listReadyPoolsByFingerprint.mockResolvedValue([]);
    claimPendingPool.mockResolvedValue({
      claimed: true,
      pool: pool({ id: "new", status: "PENDING" }),
    });

    const result = await resolveInterviewPool({
      userId: "u1",
      fingerprint: "fp-1",
      profile,
    });

    expect(result).toMatchObject({ status: "generate" });
    expect(claimPendingPool).toHaveBeenCalledWith({
      fingerprint: "fp-1",
      roleFamily: "frontend-engineering",
      seniorityBand: "senior",
      coreSkills: ["css", "react", "typescript"],
      promptVersion: "interview-pool-v1",
    });
  });

  it("grows the library when every compatible pool is already used", async () => {
    listReadyPoolsByFingerprint.mockResolvedValue([
      pool({ id: "p1", poolVersion: 1 }),
    ]);
    listUserPoolIdsAmong.mockResolvedValue(new Set(["p1"]));
    claimPendingPool.mockResolvedValue({
      claimed: true,
      pool: pool({ id: "p2", status: "PENDING", poolVersion: 2 }),
    });

    const result = await resolveInterviewPool({
      userId: "u1",
      fingerprint: "fp-1",
      profile,
    });

    expect(result).toMatchObject({ status: "generate" });
  });

  it("returns pending when another request holds the generation lock and nothing is ready", async () => {
    listReadyPoolsByFingerprint.mockResolvedValue([]);
    claimPendingPool.mockResolvedValue({ claimed: false });

    const result = await resolveInterviewPool({
      userId: "u1",
      fingerprint: "fp-1",
      profile,
    });

    expect(result).toEqual({ status: "pending" });
  });

  it("never blocks the user: recycles a used pool if generation is locked", async () => {
    listReadyPoolsByFingerprint.mockResolvedValue([
      pool({ id: "p1", poolVersion: 1 }),
    ]);
    listUserPoolIdsAmong.mockResolvedValue(new Set(["p1"]));
    claimPendingPool.mockResolvedValue({ claimed: false });

    const result = await resolveInterviewPool({
      userId: "u1",
      fingerprint: "fp-1",
      profile,
    });

    expect(result).toMatchObject({ status: "reuse", recycled: true });
    if (result.status === "reuse") {
      expect(result.pool.id).toBe("p1");
    }
  });
});
