import "server-only";

import { AlignmentType, Document, Packer, Paragraph, TextRun } from "docx";
import { sanitizePdfText } from "@/lib/pdf/text-layout";

const PAGE_WIDTH_TWIPS = 12240;
const PAGE_HEIGHT_TWIPS = 15840;
const MARGIN_TWIPS = 1440;
const BODY_HALF_POINTS = 21;
const LINE_TWIPS = 300;
const PARAGRAPH_AFTER_TWIPS = 140;
const INK = "161A18";

function toParagraphs(text: string) {
  return sanitizePdfText(text, { trim: false })
    .split(/\n{2,}/)
    .map((block) => block.replace(/\n+/g, " ").trim())
    .filter(Boolean);
}

export async function renderCoverLetterDocx(text: string): Promise<Uint8Array> {
  const blocks = toParagraphs(text);
  const children = (blocks.length > 0 ? blocks : [""]).map(
    (paragraph) =>
      new Paragraph({
        children: [
          new TextRun({
            text: paragraph,
            font: "Inter",
            size: BODY_HALF_POINTS,
            color: INK,
          }),
        ],
        alignment: AlignmentType.LEFT,
        spacing: {
          line: LINE_TWIPS,
          lineRule: "auto",
          after: PARAGRAPH_AFTER_TWIPS,
        },
      }),
  );

  const doc = new Document({
    title: "Cover letter",
    creator: "HireLens",
    description: "Cover letter generated by HireLens",
    styles: {
      default: {
        document: {
          run: { font: "Inter", size: BODY_HALF_POINTS, color: INK },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            size: { width: PAGE_WIDTH_TWIPS, height: PAGE_HEIGHT_TWIPS },
            margin: {
              top: MARGIN_TWIPS,
              right: MARGIN_TWIPS,
              bottom: MARGIN_TWIPS,
              left: MARGIN_TWIPS,
            },
          },
        },
        children,
      },
    ],
  });

  return new Uint8Array(await Packer.toBuffer(doc));
}
