import type { Command } from "./types";

const BASE_COMMANDS: Command[] = [
  {
    id: "page-dashboard",
    label: "Dashboard",
    description: "Your overview",
    keywords: ["home", "overview", "summary"],
    href: "/dashboard",
    group: "pages",
  },
  {
    id: "page-resumes",
    label: "Resumes",
    description: "Your resume library",
    keywords: ["cv", "job titles", "library"],
    href: "/dashboard/resumes",
    group: "pages",
  },
  {
    id: "page-jobs",
    label: "Saved jobs",
    description: "Track your applications",
    keywords: ["applications", "tracker", "board", "status"],
    href: "/dashboard/jobs",
    group: "pages",
  },
  {
    id: "page-documents",
    label: "AI documents",
    description: "Cover letters, emails and more",
    keywords: ["cover letter", "email", "generated", "improved resume"],
    href: "/dashboard/documents",
    group: "pages",
  },
  {
    id: "page-interview",
    label: "Interview practice",
    description: "Weekly interview questions",
    keywords: ["interview", "questions", "prepare", "readiness", "streak"],
    href: "/dashboard/interview",
    group: "pages",
  },
  {
    id: "page-help",
    label: "Help",
    description: "Guides and support",
    keywords: ["support", "guide", "faq", "how to"],
    href: "/dashboard/help",
    group: "pages",
  },
  {
    id: "page-settings",
    label: "Account settings",
    description: "Password, email and account",
    keywords: ["profile", "settings", "preferences", "account"],
    href: "/settings/account",
    group: "pages",
  },
  {
    id: "action-add-resume",
    label: "Add a resume",
    description: "Upload a new resume",
    keywords: ["upload", "cv", "new resume", "import"],
    href: "/dashboard/resumes",
    group: "actions",
  },
  {
    id: "action-create-application",
    label: "Create application",
    description: "Save a job you are interested in",
    keywords: ["save job", "new job", "add job", "apply", "new application"],
    href: "/dashboard/applications",
    group: "actions",
  },
  {
    id: "action-paste-job",
    label: "Paste a job posting",
    description: "Fill in a job from a copied listing",
    keywords: ["extract", "import job", "linkedin", "indeed", "listing"],
    href: "/dashboard/applications",
    group: "actions",
  },
  {
    id: "action-report-problem",
    label: "Report a problem",
    description: "Tell us something is broken",
    keywords: ["bug", "feedback", "issue", "broken", "contact"],
    href: "/dashboard/help",
    group: "actions",
  },
  {
    id: "account-password",
    label: "Add or change password",
    description: "Opens account settings",
    keywords: ["password", "security", "sign in", "credentials", "login"],
    href: "/settings/account",
    group: "account",
  },
  {
    id: "account-verify-email",
    label: "Verify your email",
    description: "Opens account settings",
    keywords: ["verify", "confirm email", "verification", "email address"],
    href: "/settings/account",
    group: "account",
  },
  {
    id: "account-pause",
    label: "Pause account",
    description: "Opens account settings",
    keywords: ["disable", "deactivate", "take a break"],
    href: "/settings/account",
    group: "account",
  },
  {
    id: "account-delete",
    label: "Delete account",
    description: "Opens account settings",
    keywords: ["remove", "close account", "delete my data", "erase"],
    href: "/settings/account",
    group: "account",
  },
];

const ADMIN_COMMANDS: Command[] = [
  {
    id: "admin-home",
    label: "Administration",
    description: "Admin overview",
    keywords: ["admin", "operations"],
    href: "/admin",
    group: "admin",
  },
  {
    id: "admin-users",
    label: "Admin: Users",
    description: "Accounts, roles and status",
    keywords: ["admin", "accounts", "members", "impersonate", "promote"],
    href: "/admin/users",
    group: "admin",
  },
  {
    id: "admin-usage",
    label: "Admin: Feature usage",
    description: "AI usage by feature",
    keywords: ["admin", "analytics", "ai usage", "statistics"],
    href: "/admin/usage",
    group: "admin",
  },
  {
    id: "admin-errors",
    label: "Admin: Errors",
    description: "Recent errors from Sentry",
    keywords: ["admin", "sentry", "exceptions", "crashes"],
    href: "/admin/errors",
    group: "admin",
  },
  {
    id: "admin-audit-log",
    label: "Admin: Audit log",
    description: "Sensitive admin actions",
    keywords: ["admin", "history", "activity", "audit"],
    href: "/admin/audit-log",
    group: "admin",
  },
  {
    id: "admin-health",
    label: "Admin: System health",
    description: "Database and backlog status",
    keywords: ["admin", "status", "uptime", "database"],
    href: "/admin/health",
    group: "admin",
  },
  {
    id: "admin-bug-reports",
    label: "Admin: Bug reports",
    description: "Reports from users",
    keywords: ["admin", "triage", "support", "reports"],
    href: "/ops-console",
    group: "admin",
  },
];

export function buildCommands(input: { isAdmin: boolean }): Command[] {
  return input.isAdmin ? [...BASE_COMMANDS, ...ADMIN_COMMANDS] : BASE_COMMANDS;
}

export const baseCommandIds = BASE_COMMANDS.map((command) => command.id);
export const adminCommandIds = ADMIN_COMMANDS.map((command) => command.id);
